### ISSUE TITLE
Incorrect subtotal numbers

### ISSUE THREAD

**Issue by chrisrosset** [Dacteev/invoice-latex#1]
I've generated the demo invoice and it looks wonderful but the running subtotal numbers are showing up wrong. Seems like an issue with late macro/variable evaluation as the final `\subtotal` value gets printed in all the rows.

![2015-04-14-212217_645x644_scrot](https://cloud.githubusercontent.com/assets/1103294/7146561/5e608a88-e2ec-11e4-9365-6b513fe31849.png)

**Comment by euskadi31** [comment]
Hello,

Yes the problem is known, I haven't managed to fix it ... and I have not had time to take care of it :(
